name: "scan2html"
repository: github.com/fatihtokus/scan2html
version: "0.0.3"
usage: scan targets into a smart html file
description: |-
  A Trivy plugin that scans and outputs the results to a html file.
  trivy scan2html [-h,--help] command target filename
platforms:
  -
    uri: https://github.com/fatihtokus/scan2html/releases/download/v0.0.1/trivy-scan2html.tar.gz
    bin: ./scan2html
