name: "scan2html"
repository: github.com/fatihtokus/scan2html
version: "0.0.1"
usage: scan targets into a smart html file
description: |-
  A Trivy plugin that scans and outputs the results to a html file.
  trivy scan2html [-h,--help] command target filename
platforms:
  - selector:
      os: windows
    uri: ./scan2html
    bin: ./scan2html.sh
  -
    uri: ./scan2html
    bin: ./scan2html
