name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      reportTemplate: 'report_template.html'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Preparing report_template.html
        run: |
          # copy util js file
          cat
          {
          # copy report file except the last 9 lines
          head -n -9 'src/report.html'
          echo ''
          echo '<script>'
          cat 'src/js/utils.js'
          echo ''
          # copy js file except the last 15 lines
          head -n -15 'src/js/report.js'
          echo ''
          echo '</script>'
          } >"$reportTemplate"
          
          cat "$reportTemplate"
      - name: Compress
        run: tar -zcvf scan2html.tar.gz scan2html "$reportTemplate" LICENSE results.json
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            scan2html.tar.gz
