name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Preparing report_template.html
        run: |
          reportTemplate="report_template.html"
          
          # copy report file except the last 9 lines
          head -n -9 "src/report.html" > "tmp.html"
          cat "tmp.html" >>"$reportTemplate"
          
          # copy util js file
          cat
          {
          echo ''
          echo '<script>'
          cat  "src/js/utils.js"
          echo ''
          } >>"$reportTemplate"
          # copy js file except the last 15 lines
          head -n -15 "src/js/report.js" > "$reportTemplate"
          cat
          {
          echo '</script>'
          } >>"$reportTemplate"
          
          cat "$reportTemplate"
      - name: Compress
        run: tar -zcvf scan2html.tar.gz scan2html report_template.html LICENSE results.json
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            scan2html.tar.gz
